name: mobile
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  url_launcher: ^6.0.9
  smooth_page_indicator: ^1.1.0
  flutter_local_notifications: ^8.1.1+1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1


flutter:
  uses-material-design: true
  assets: 
    - lib/assets/login_screen_background.jpg

